site:
  title: Spark Cassandra Connector documentation
  url: /
  # start_page: index.adoc

content:
  sources:
    - url: ../
      start_path: doc
      branches: HEAD

ui:
  bundle:
    url: https://github.com/ianjevans/antora-ui-datastax/releases/download/v0.1/ui-bundle.zip
  supplemental_files: ./supplemental-ui
