site:
  title: Spark Cassandra Connector documentation
  start_page: doc::quickstart::quick_start.adoc

content:
  sources:
    - url: .
      start_path: doc

ui:
  bundle:
    url: https://github.com/ianjevans/antora-ui-datastax/releases/download/v0.1/ui-bundle.zip
